package SubjectiefRecht.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Casus = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IEvaluatieResultaat = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LijstMetRechtsbetrekkingen = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LijstMetRechtshandelingen = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rechtsbetrekking = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RechtsgevolgVeroorzaker = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rechtshandeling = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rechtssubject = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsSubject = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsbetrekking = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Casus;
      case 1:
        return props_IEvaluatieResultaat;
      case 2:
        return props_LijstMetRechtsbetrekkingen;
      case 3:
        return props_LijstMetRechtshandelingen;
      case 4:
        return props_Rechtsbetrekking;
      case 5:
        return props_RechtsgevolgVeroorzaker;
      case 6:
        return props_Rechtshandeling;
      case 7:
        return props_Rechtssubject;
      case 8:
        return props_ReferentieNaarRechtsSubject;
      case 9:
        return props_ReferentieNaarRechtsbetrekking;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
