package Datum.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Datum = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_DatumTijd = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Tijd = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VerschilTussen = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Datum;
      case 1:
        return props_DatumTijd;
      case 2:
        return props_Tijd;
      case 3:
        return props_VerschilTussen;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
