package ObjectiefRecht.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_AanspraakNaIngebrekeStellingPlicht = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractArtikel = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractKenmerk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstractReferentieNaarKenmerk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstracteExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_AbstracteVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Actie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Afleidingsregel = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Artikel = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Concept = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Conditie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ConditieAlle = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ConditieEen = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ConditieGeen = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Context = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_DatumDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_DelenExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_EnkeleVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Enumeratie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_EnumeratieDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_EnumeratieElement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ExpressieVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_FeitelijkeHandelingMetRechtsgevolg = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_GebeurtenisMetRechtsgevolg = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_GeheelGetalDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Gelijkstelling = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ImmuniteitGeenbevoegdheid = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IsGelijk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IsGroterDan = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IsKleinerDan = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IsOpgegeven = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IsWaar = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_JaNeeDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kenmerk = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Kenmerk2 = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_KenmerkMetReferentieNaarOnderwerp = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_KenmerkReferentie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_KenmerkReferentieNaarSubject = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_KrachtigeAanspraakFataleVerplichtig = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Lidwoord = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LidwoordDe = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LidwoordHet = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_MaterieleVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_MinExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Object = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ObjectDataType = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Onderwerp = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_OnderwerpDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OptioneleBevoegdheidOptioneleGehoudenheid = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PlusExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RechtsSubject = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rechtsbetrekking = new ConceptPresentationBuilder().deprecated(MetaAdapterFactory.getProperty(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x611073d615228d0dL, 0x25be3715c7da8818L, "initieel"), MetaAdapterFactory.getReferenceLink(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x611073d615228d0dL, 0x611073d615228d2dL, "rechtssubjectMetRecht"), MetaAdapterFactory.getReferenceLink(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x611073d615228d0dL, 0x611073d615228d2eL, "rechtssubjectMetPlicht"), MetaAdapterFactory.getReferenceLink(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x611073d615228d0dL, 0x218d2fe3c8aff5f6L, "onderwerp")).create();
  private final ConceptPresentation props_Rechtsgevolg = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RechtsgevolgVeroorzakers = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rechtshandeling = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_ReeelGetalDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarArtikel = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarEnumeratie = new ConceptPresentationBuilder().deprecated().create();
  private final ConceptPresentation props_ReferentieNaarOnderwerp = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsHandeling = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsbetrekking = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsgevolg = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtsgevolgVeroorzaker = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarRechtssubject = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarReferentieNaarOnderwerp = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarReferentieNaarSubject = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ReferentieNaarVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Regel = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RekenExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RijVanKaraktersDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SamengesteldeVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SubjectDataType = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TenMinste = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TijdDatatype = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TijdsverloopMetRechtsgevolg = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Toestand = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Variabele = new ConceptPresentationBuilder().deprecated(MetaAdapterFactory.getReferenceLink(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x76ccb41bf386dd7eL, 0x1fabc0b15d5dc56eL, "onderwerp2"), MetaAdapterFactory.getReferenceLink(0x8dc4b25f4c49400eL, 0xac370fd230db702cL, 0x76ccb41bf386dd7eL, 0x1fabc0b15d5dc570L, "kenmerk2")).create();
  private final ConceptPresentation props_VermenigvuldigenExpressie = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VerplichteBevoegdheidVerplichteGehoudenheid = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VerschilTussen = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VormVoorwaarde = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VrijeTekst = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_VrijheidGeenaanspraak = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ZwakkeAanspraakZwakkePlicht = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_AanspraakNaIngebrekeStellingPlicht;
      case 1:
        return props_AbstractArtikel;
      case 2:
        return props_AbstractDatatype;
      case 3:
        return props_AbstractKenmerk;
      case 4:
        return props_AbstractReferentieNaarKenmerk;
      case 5:
        return props_AbstracteExpressie;
      case 6:
        return props_AbstracteVoorwaarde;
      case 7:
        return props_Actie;
      case 8:
        return props_Afleidingsregel;
      case 9:
        return props_Artikel;
      case 10:
        return props_Concept;
      case 11:
        return props_Conditie;
      case 12:
        return props_ConditieAlle;
      case 13:
        return props_ConditieEen;
      case 14:
        return props_ConditieGeen;
      case 15:
        return props_Context;
      case 16:
        return props_DatumDatatype;
      case 17:
        return props_DelenExpressie;
      case 18:
        return props_EnkeleVoorwaarde;
      case 19:
        return props_Enumeratie;
      case 20:
        return props_EnumeratieDatatype;
      case 21:
        return props_EnumeratieElement;
      case 22:
        return props_ExpressieVoorwaarde;
      case 23:
        return props_FeitelijkeHandelingMetRechtsgevolg;
      case 24:
        return props_GebeurtenisMetRechtsgevolg;
      case 25:
        return props_GeheelGetalDatatype;
      case 26:
        return props_Gelijkstelling;
      case 27:
        return props_ImmuniteitGeenbevoegdheid;
      case 28:
        return props_IsGelijk;
      case 29:
        return props_IsGroterDan;
      case 30:
        return props_IsKleinerDan;
      case 31:
        return props_IsOpgegeven;
      case 32:
        return props_IsWaar;
      case 33:
        return props_JaNeeDatatype;
      case 34:
        return props_Kenmerk;
      case 35:
        return props_Kenmerk2;
      case 36:
        return props_KenmerkMetReferentieNaarOnderwerp;
      case 37:
        return props_KenmerkReferentie;
      case 38:
        return props_KenmerkReferentieNaarSubject;
      case 39:
        return props_KrachtigeAanspraakFataleVerplichtig;
      case 40:
        return props_Lidwoord;
      case 41:
        return props_LidwoordDe;
      case 42:
        return props_LidwoordHet;
      case 43:
        return props_MaterieleVoorwaarde;
      case 44:
        return props_MinExpressie;
      case 45:
        return props_Object;
      case 46:
        return props_ObjectDataType;
      case 47:
        return props_Onderwerp;
      case 48:
        return props_OnderwerpDatatype;
      case 49:
        return props_OptioneleBevoegdheidOptioneleGehoudenheid;
      case 50:
        return props_PlusExpressie;
      case 51:
        return props_RechtsSubject;
      case 52:
        return props_Rechtsbetrekking;
      case 53:
        return props_Rechtsgevolg;
      case 54:
        return props_RechtsgevolgVeroorzakers;
      case 55:
        return props_Rechtshandeling;
      case 56:
        return props_ReeelGetalDatatype;
      case 57:
        return props_ReferentieNaarArtikel;
      case 58:
        return props_ReferentieNaarEnumeratie;
      case 59:
        return props_ReferentieNaarOnderwerp;
      case 60:
        return props_ReferentieNaarRechtsHandeling;
      case 61:
        return props_ReferentieNaarRechtsbetrekking;
      case 62:
        return props_ReferentieNaarRechtsgevolg;
      case 63:
        return props_ReferentieNaarRechtsgevolgVeroorzaker;
      case 64:
        return props_ReferentieNaarRechtssubject;
      case 65:
        return props_ReferentieNaarReferentieNaarOnderwerp;
      case 66:
        return props_ReferentieNaarReferentieNaarSubject;
      case 67:
        return props_ReferentieNaarVoorwaarde;
      case 68:
        return props_Regel;
      case 69:
        return props_RekenExpressie;
      case 70:
        return props_RijVanKaraktersDatatype;
      case 71:
        return props_SamengesteldeVoorwaarde;
      case 72:
        return props_SubjectDataType;
      case 73:
        return props_TenMinste;
      case 74:
        return props_TijdDatatype;
      case 75:
        return props_TijdsverloopMetRechtsgevolg;
      case 76:
        return props_Toestand;
      case 77:
        return props_Variabele;
      case 78:
        return props_VermenigvuldigenExpressie;
      case 79:
        return props_VerplichteBevoegdheidVerplichteGehoudenheid;
      case 80:
        return props_VerschilTussen;
      case 81:
        return props_VormVoorwaarde;
      case 82:
        return props_VrijeTekst;
      case 83:
        return props_VrijheidGeenaanspraak;
      case 84:
        return props_ZwakkeAanspraakZwakkePlicht;
    }
    throw new IllegalStateException("Unknown concept " + c);
  }
}
