package ObjectiefRecht.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.RefCellCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.InlineCellProvider;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;

public class ReferentieNaarVoorwaardeRechtsbetrekking_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_uvh17u_a(editorContext, node);
  }
  private EditorCell createCollection_uvh17u_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_uvh17u_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_uvh17u_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_uvh17u_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_uvh17u_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_uvh17u_d0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_uvh17u_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "-");
    editorCell.setCellId("Constant_uvh17u_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_uvh17u_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
    editorCell.setCellId("Constant_uvh17u_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_uvh17u_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "er is een rechtsbetrekking");
    editorCell.setCellId("Constant_uvh17u_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefCell_uvh17u_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("Rechtsbetrekking");
    provider.setNoTargetText("<no Rechtsbetrekking>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new ReferentieNaarVoorwaardeRechtsbetrekking_Editor._Inline_uvh17u_a3a());
    editorCell = provider.createEditorCell(editorContext);
    if (editorCell.getRole() == null) {
      editorCell.setReferenceCell(true);
      editorCell.setRole("Rechtsbetrekking");
    }
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  public static class _Inline_uvh17u_a3a extends InlineCellProvider {
    public _Inline_uvh17u_a3a() {
      super();
    }
    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }
    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_uvh17u_a0d0(editorContext, node);
    }
    private EditorCell createProperty_uvh17u_a0d0(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name");
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      if (attributeConcept != null) {
        EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
        return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
      } else
      return editorCell;
    }
  }
}
